"""Your migration message

Revision ID: 373a115984c3
Revises: 0edde2a25f6a
Create Date: 2024-08-13 03:26:04.717717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373a115984c3'
down_revision = '0edde2a25f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_included', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['video_name'])
        batch_op.create_unique_constraint(None, ['file_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_included', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('file_name')
        batch_op.drop_column('video_name')

    # ### end Alembic commands ###
