"""Initial Migration

Revision ID: 6782d65520be
Revises: 
Create Date: 2024-08-02 00:33:57.658682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6782d65520be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_book')
    op.drop_table('song_catalog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_catalog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='song_catalog_pkey'),
    sa.UniqueConstraint('file_name', name='song_catalog_file_name_key'),
    sa.UniqueConstraint('file_path', name='song_catalog_file_path_key'),
    sa.UniqueConstraint('song_name', name='song_catalog_song_name_key')
    )
    op.create_table('song_book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='song_book_pkey'),
    sa.UniqueConstraint('song_name', name='song_book_song_name_key')
    )
    # ### end Alembic commands ###
