"""video table

Revision ID: a010f3978649
Revises: d376bdbd265a
Create Date: 2024-08-05 03:55:26.607822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a010f3978649'
down_revision = 'd376bdbd265a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_included', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['video_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_included', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
