"""Add NewTable

Revision ID: d2cd400c1b63
Revises: 6782d65520be
Create Date: 2024-08-05 03:07:43.990937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cd400c1b63'
down_revision = '6782d65520be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos_included',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('song_name'),
    sa.UniqueConstraint('video_path')
    )
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey'),
    sa.UniqueConstraint('file_name', name='test_table_file_name_key'),
    sa.UniqueConstraint('file_path', name='test_table_file_path_key'),
    sa.UniqueConstraint('song_name', name='test_table_song_name_key')
    )
    op.drop_table('videos_included')
    # ### end Alembic commands ###
