"""Add NewTable

Revision ID: d376bdbd265a
Revises: d2cd400c1b63
Create Date: 2024-08-05 03:40:55.074546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd376bdbd265a'
down_revision = 'd2cd400c1b63'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('videos_included', sa.Column('video_name', sa.String(), nullable=True))
    # Optionally, set a default value if appropriate
    op.execute('UPDATE videos_included SET video_name = \'default_value\' WHERE video_name IS NULL')
    op.alter_column('videos_included', 'video_name', existing_type=sa.String(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_included', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('video_name')

    # ### end Alembic commands ###
